# Generated by Django 5.1.6 on 2025-03-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmassage",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="chatmassage",
            name="sender",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_free",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.DeleteModel(
            name="ChatMassage",
        ),
    ]
