# Generated by Django 5.1.6 on 2025-03-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_remove_chatmassage_receiver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Admin"), (1, "Branch admin"), (2, "Agent")],
                null=True,
            ),
        ),
    ]
