# Generated by Django 5.1.6 on 2025-02-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablefield",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("CharField", "Character Field"),
                    ("IntegerField", "Integer Field"),
                    ("DateField", "Date Field"),
                    ("BooleanField", "Boolean Field"),
                ],
                default="CharField",
                max_length=50,
            ),
        ),
    ]
