# Generated by Django 5.1.6 on 2025-03-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Complete", "Complete"),
                    ("pending", "Pending"),
                    ("Cancel", "Cancel"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
