# Generated by Django 5.1.6 on 2025-03-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_customer_phone_number_and_more"),
        ("core", "0003_alter_transactions_status"),
    ]

    operations = []
